### ISSUE TITLE
crash after command 'clear'

### ISSUE THREAD

**Issue by kicumkicum** [kicumkicum/vknplayer#11]
log:
path.existsSync is now called `fs.existsSync`.
TypeError: Cannot set property 'style' of null
    at PlayList._colorizePlayingTrack (/home/oleg/project/rest/vknplayer/app/ui/console/panels/lib/playlist.js:252:43)
    at PlayList._afterPlay (/home/oleg/project/rest/vknplayer/app/ui/console/panels/lib/playlist.js:125:7)
    at emit (events.js:117:20)
    at Player._play (/home/oleg/project/rest/vknplayer/app/service/lib/player/lib/player.js:158:7)
    at Player.next (/home/oleg/project/rest/vknplayer/app/service/lib/player/lib/player.js:121:10)
    at Player._afterStop (/home/oleg/project/rest/vknplayer/app/service/lib/player/lib/player.js:175:8)
    at emit (events.js:95:17)
    at StupidPlayer._emit (/home/oleg/project/rest/vknplayer/app/service/lib/player/stupid-player/lib/stupid-player.js:153:7)
    at StupidPlayer._makeDecoder (/home/oleg/project/rest/vknplayer/app/service/lib/player/stupid-player/lib/stupid-player.js:110:8)
    at ClientRequest.g (events.js:180:16)

**Comment by kicumkicum** [comment]
Error can not be played
