### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kicumkicum** [kicumkicum/vknplayer#12]
TypeError: Cannot set property 'style' of null
    at PlayList._colorizePlayingTrack (/home/banana/projects/vknplayer/app/ui/console/panels/lib/playlist.js:252:43)
    at PlayList._afterPlay (/home/banana/projects/vknplayer/app/ui/console/panels/lib/playlist.js:125:7)
    at emit (events.js:117:20)
    at Player._play (/home/banana/projects/vknplayer/app/service/lib/player/lib/player.js:158:7)
    at Player.next (/home/banana/projects/vknplayer/app/service/lib/player/lib/player.js:121:10)
    at Player._afterStop (/home/banana/projects/vknplayer/app/service/lib/player/lib/player.js:175:8)
    at emit (events.js:95:17)
    at StupidPlayer._emit (/home/banana/projects/vknplayer/app/service/lib/player/stupid-player/lib/stupid-player.js:153:7)
    at StupidPlayer._makeDecoder (/home/banana/projects/vknplayer/app/service/lib/player/stupid-player/lib/stupid-player.js:110:8)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming](http.js:1688:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete](http.js:121:23)

**Comment by kicumkicum** [comment]
dublicate #11
