### ISSUE TITLE
v0.0.42 not start

### ISSUE THREAD

**Issue by kicumkicum** [kicumkicum/vknplayer#54]
``` bash
$ ./vknplayer.js 
path.existsSync is now called `fs.existsSync`.
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at emit (events.js:74:15)
    at VK._requestWrapper (/Users/oleg/projects/vknplayer/app/api/lib/vk/api/vk.js:34:8)
    at VK.getUserId (/Users/oleg/projects/vknplayer/app/api/lib/vk/api/vk.js:94:14)
    at Console.init (/Users/oleg/projects/vknplayer/app/ui/console/lib/console.js:40:4)
    at UI.init (/Users/oleg/projects/vknplayer/app/ui/index.js:30:16)
    at Vknp._initUI (/Users/oleg/projects/vknplayer/app/lib/app.js:243:10)
    at Vknp.start (/Users/oleg/projects/vknplayer/app/lib/app.js:19:7)
    at Object.<anonymous> (/Users/oleg/projects/vknplayer/vknplayer.js:17:5)
    at Module._compile (module.js:456:26)
```

**Comment by kicumkicum** [comment]
fix in develop allready
